<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Услуги");
?><br>

 <?$APPLICATION->IncludeComponent(
	"bitrix:news",
	"projects",
	Array(
		"ADD_ELEMENT_CHAIN" => "Y",
		"ADD_SECTIONS_CHAIN" => "Y",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "Y",
		"AJAX_OPTION_JUMP" => "Y",
		"AJAX_OPTION_SHADOW" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"BROWSER_TITLE" => "-",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "3600000",
		"CACHE_TYPE" => "A",
		"CHECK_DATES" => "Y",
		"COLOR_NEW" => "3E74E6",
		"COLOR_OLD" => "C0C0C0",
		"COMPONENT_TEMPLATE" => "projects",
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO",
		"DETAIL_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"DETAIL_DISPLAY_BOTTOM_PAGER" => "Y",
		"DETAIL_DISPLAY_TOP_PAGER" => "N",
		"DETAIL_FIELD_CODE" => array(0=>"NAME",1=>"PREVIEW_TEXT",2=>"PREVIEW_PICTURE",3=>"DETAIL_TEXT",4=>"DETAIL_PICTURE",5=>"DATE_ACTIVE_FROM",6=>"",),
		"DETAIL_PAGER_SHOW_ALL" => "N",
		"DETAIL_PAGER_TEMPLATE" => "modern",
		"DETAIL_PAGER_TITLE" => "Услуги",
		"DETAIL_PROPERTY_CODE" => array(0=>"SHOW_FRONT_PAGE",1=>"FORM_ORDER",2=>"SERVICE_TYPE",3=>"ICON_NAME",4=>"DOCUMENTS_TITLE",5=>"GALLERY_TITLE",6=>"LINK_FAQ",7=>"LINK_REVIEWS",8=>"LINK_STAFF",9=>"LINK_PROJECTS",10=>"BANNER_VISIBLE",11=>"BANNER_BUTTON_TEXT",12=>"BANNER_TEXT_COLOR",13=>"BANNER_BG_COLOR",14=>"BANNER_TEXT",15=>"INFO_SITE",16=>"INFO_SCOPE",17=>"INFO_DATE",18=>"INFO_CLIENT",19=>"DOCUMENTS",20=>"MORE_PHOTO",21=>"BANNER_IMAGE",22=>"BANNER_BG",23=>"",),
		"DETAIL_SET_CANONICAL_URL" => "N",
		"DISPLAY_AS_RATING" => "rating",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_DATE" => "Y",
		"DISPLAY_NAME" => "Y",
		"DISPLAY_PANEL" => "N",
		"DISPLAY_PICTURE" => "Y",
		"DISPLAY_PREVIEW_TEXT" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"FONT_MAX" => "50",
		"FONT_MIN" => "10",
		"HIDE_LINK_WHEN_NO_DETAIL" => "Y",
		"IBLOCK_ID" => "14",
		"IBLOCK_TYPE" => "marsd_bitcorp_s1",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"LIST_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"LIST_FIELD_CODE" => array(0=>"NAME",1=>"PREVIEW_TEXT",2=>"PREVIEW_PICTURE",3=>"DETAIL_TEXT",4=>"DATE_ACTIVE_FROM",5=>"",),
		"LIST_PROPERTY_CODE" => array(0=>"SHOW_FRONT_PAGE",1=>"FORM_ORDER",2=>"SERVICE_TYPE",3=>"ICON_NAME",4=>"LINK_FAQ",5=>"LINK_REVIEWS",6=>"LINK_STAFF",7=>"",),
		"LIST_USE_SHARE" => "N",
		"MEDIA_PROPERTY" => "",
		"MESSAGE_404" => "",
		"META_DESCRIPTION" => "-",
		"META_KEYWORDS" => "-",
		"NEWS_COUNT" => "20",
		"NUM_DAYS" => "30",
		"NUM_NEWS" => "3",
		"OTHER_ITEMS_TITLE" => "Другие новости",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => "modern",
		"PAGER_TITLE" => "Услуги",
		"PERIOD_NEW_TAGS" => "",
		"PREVIEW_TRUNCATE_LEN" => "",
		"PROJECTS_BLOCK_DESCRIPTION" => "Наша компания оказывает полный спектр услуг. У нашей компании прекрасная репутация, и мы уже успели завоевать доверие и расположение своих клиентов. Во многом это связано с широким спектром услуг, предоставляемых нашей компанией, а также высоким качеством обслуживания.",
		"PROJECTS_SHOW_DESCRIPTION" => "Y",
		"SECTION_USER_FIELDS" => array(0=>"UF_SECTION_TITLE",1=>"UF_SECTION_DESCR",2=>"UF_BG_COLOR",3=>"UF_TITLE_BG",4=>"UF_SECTION_SIZE",5=>"UF_SIMPLE_BLOCK",6=>"UF_INVERSE_TEXT",7=>"",),
		"SEF_FOLDER" => "/services/",
		"SEF_MODE" => "Y",
		"SEF_URL_TEMPLATES" => array("news"=>"","section"=>"","detail"=>"#ELEMENT_CODE#/",),
		"SERVICES_BLOCK_DESCRIPTION" => "",
		"SERVICE_ITEM_HEIGHT" => "250",
		"SERVICE_LINE_COUNT" => "3",
		"SERVICE_SHOW_DESCRIPTION" => "Y",
		"SET_LAST_MODIFIED" => "N",
		"SET_STATUS_404" => "Y",
		"SET_TITLE" => "Y",
		"SHARE_HANDLERS" => array(0=>"facebook",1=>"delicious",2=>"mailru",3=>"twitter",4=>"lj",5=>"vk",),
		"SHARE_HIDE" => "N",
		"SHARE_SHORTEN_URL_KEY" => "",
		"SHARE_SHORTEN_URL_LOGIN" => "",
		"SHARE_TEMPLATE" => "",
		"SHOW_404" => "N",
		"SHOW_IBLOCK_DESCRIPTION" => "Y",
		"SHOW_OTHER_NEWS" => "Y",
		"SHOW_SECTION_NAME" => "Y",
		"SHOW_SECTION_PREVIEW_DESCRIPTION" => "Y",
		"SLIDER_PROPERTY" => "",
		"SORT_BY1" => "SORT",
		"SORT_BY2" => "ID",
		"SORT_ORDER1" => "ASC",
		"SORT_ORDER2" => "ASC",
		"STRICT_SECTION_CHECK" => "N",
		"TAGS_CLOUD_ELEMENTS" => "150",
		"TAGS_CLOUD_WIDTH" => "100%",
		"TEMPLATE_THEME" => "blue",
		"USE_CATEGORIES" => "N",
		"USE_CHESS_BACKLIGHT" => "Y",
		"USE_FILTER" => "N",
		"USE_PERMISSIONS" => "N",
		"USE_RATING" => "N",
		"USE_RSS" => "N",
		"USE_SEARCH" => "N",
		"USE_SHARE" => "Y",
		"YANDEX" => "N"
	)
);?><br>
 <br><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>